# Generated by Django 5.0 on 2023-12-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='studybud/static/images/avatar.svg', null=True, upload_to=''),
        ),
    ]
